name: Client build test

on:
    push:
        branches:
          - "real"
    pull_request:
        branches:
          - "master" 
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['21.x']
        
    steps:
      - uses: actions/checkout@v4
      - name: set up environment npm install
        run: cd client && ./build.sh
      - name: test the index.html is generated
        run: test chrome-extension/index.html 
